Several changes and fixes
notspiff/audiodecoder.timidity pull request #22
Opened 2019-08-17 15:44 UTC by AlwinEsch

The fix is related to https://github.com/xbmc/audiodecoder.timidity/pull/19, timity was mainly designed as own app and not constructed to handle several files together. Shortly before one file is finished, open Kodi the next, in static this brings a crash. With shared a independent memory is created by `dlopen` on next playback. Anyway, the test works fine.

Further was still `dlopen` inside which found nothing :smile: and created addon errors.

2019-08-17 18:09 UTC, AlwinEsch commented
Now works also on Windows, after few fixes was the compile and playback OK.

2019-08-19 11:27 UTC, Rechi requested changes
Removing WindowsStore from appveyor CI is wrong.
Can you try with `Visual Studio 2017` image and `Visual Studio 15` generator. That's also what's Jenkins uses and works locally here.

2019-08-19 11:37 UTC, Rechi commented on appveyor.yml
> +      WINSTORE: -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0.17763.0"
Why change SDK version?

2019-08-19 11:40 UTC, AlwinEsch commented on appveyor.yml
> +      WINSTORE: -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0.17763.0"
Thought also related. Can remove again.

2019-08-19 11:41 UTC, Rechi commented on appveyor.yml
> +      WINSTORE: -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0.17763.0"
No, Leia uses SDK 10.0.16299.0 for UWP.

2019-08-19 21:21 UTC, AlwinEsch commented on appveyor.yml
> +      WINSTORE: -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0.17763.0"
Thanks @Rechi this change has fixed it.

2019-08-19 21:22 UTC, merged